#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#define MAX_SIZE 93

struct ThreadData {
    long long *fibonacciArray;
    int n;
};


void *generateFibonacci(void *arg) {
    struct ThreadData *data = (struct ThreadData *)arg;

    data->fibonacciArray[0] = 0;
    data->fibonacciArray[1] = 1;

    for (int i = 2; i < data->n; i++) {
        data->fibonacciArray[i] = data->fibonacciArray[i - 1] + data->fibonacciArray[i - 2];
    }

    pthread_exit(NULL);
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <number_of_fibonacci_numbers>\n", argv[0]);
        return 1;
    }

    int n = atoi(argv[1]);

    if (n <= 0 || n>MAX_SIZE) {
        fprintf(stderr, "Please enter a positive integer which is less than or equal to %d",MAX_SIZE);
        return 1;
    }

    pthread_t tid;
    struct ThreadData threadData;

    long long *fibonacciArray = (long long *)malloc(n * sizeof(long long));
    if (fibonacciArray == NULL) {
        fprintf(stderr, "Memory allocation failed.\n");
        return 1;
    }

    threadData.fibonacciArray = fibonacciArray;
    threadData.n = n;


    if (pthread_create(&tid, NULL, generateFibonacci, (void *)&threadData) != 0) {
        fprintf(stderr, "Error creating thread.\n");
        return 1;
    }


    if (pthread_join(tid, NULL) != 0) {
        fprintf(stderr, "Error joining thread.\n");
        return 1;
    }

    printf("Fibonacci Sequence generated by the child thread: ");
    for (int i = 0; i < n; i++) {
        printf("%lld ", fibonacciArray[i]);
    }
    printf("\n");

    free(fibonacciArray);

    return 0;
}
